### ISSUE TITLE
Google Merchant RSS 2.0 Builder is missing special character encoding for Google Product Type

### ISSUE THREAD

**Issue by sergiFlowbox** [vojtasvoboda/oc-shopaholicfeeds-plugin#4]
Some Google Product Category fields have special characters such as "&". When generating a XML product feed, these characters are not properly encoded. This can be fixed by using [htmlspecialchars](https://www.php.net/manual/en/function.htmlspecialchars.php) when the category is appended.
![image](https://github.com/vojtasvoboda/oc-shopaholicfeeds-plugin/assets/163538360/f174715c-8484-4d85-a1b9-1ef72ca2b85c)

**Comment by vojtasvoboda** [comment]
Thanks for the PRs, new version of plugin available at the OctoberCMS market :-)
